version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: 08:00
      timezone: America/Denver
    commit-message:
      prefix: actions
    labels:
      - dependencies
    open-pull-requests-limit: 100
